---
- hosts: all
  sudo: yes
  tasks:
    - name: "Elasticsearch 1.4.0、Kibana4 BETA2とテストデータ(shakespeare.json)をダウンロード"
      get_url: url={{ item }} dest=/tmp
      with_items:
        - https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.0.deb
        - https://download.elasticsearch.org/kibana/kibana/kibana-4.0.0-BETA2.tar.gz
        - http://www.elasticsearch.org/guide/en/kibana/current/snippets/shakespeare.json
    - name: "Oracle Javaをインストールするためのaptリポジトリーを追加"
      apt_repository: repo='ppa:webupd8team/java' update_cache=yes
    - name: "Oracle Javaを自動的にインストールするための設定を書き込む"
      shell: |
        echo "oracle-java7-installer shared/accepted-oracle-license-v1-1 select true" > /tmp/oracle-license-debconf
        /usr/bin/debconf-set-selections /tmp/oracle-license-debconf
    - name: "日本語パックとOracle Javaをインストール"
      apt: name={{ item }}
      with_items:
        - language-pack-ja
        - oracle-java7-installer
    - name: "Elasticsearchをdebパッケージからインストール"
      apt: deb=/tmp/elasticsearch-1.4.0.deb
    - name: "Elasticsearchを起動してサービスを有効化"
      service: name=elasticsearch state=started enabled=yes
    - name: "Elasticsearchの起動を待つ"
      wait_for: port=9200
    - name: "Kibana4のアーカイブを展開"
      unarchive: copy=no src=/tmp/kibana-4.0.0-BETA2.tar.gz dest=/opt
    - name: "Kibana4の起動スクリプトを転送"
      copy: src=files/kibana.initscript dest=/etc/init.d/kibana mode=755
    - name: "Kibana4を起動してサービスを有効化"
      service: name=kibana state=started enabled=yes
    - name: "テストデータのマッピングを作成。これを作成しないとspeakerやplay_nameがトークナイズされてしまう"
      shell: curl -XPUT http://localhost:9200/shakespeare -d '{"mappings":{"_default_":{"properties":{"speaker":{"type":"string","index":"not_analyzed" },"play_name":{"type":"string","index":"not_analyzed"},"line_id":{"type":"integer"},"speech_number":{"type":"integer"}}}}}'
    - name: "テストデータの投入"
      shell: curl -XPUT localhost:9200/_bulk --data-binary @/tmp/shakespeare.json
