- hosts: all
  sudo: yes
  vars:
    elasticsearch_version: elasticsearch-1.5.0
    kibana_version: kibana-4.0.2-linux-x64
  tasks:
    - name: "Elasticsearch,Kibanaとテストデータ(shakespeare.json)をダウンロード"
      get_url: url={{ item }} dest=/tmp
      with_items:
        - https://download.elasticsearch.org/elasticsearch/elasticsearch/{{ elasticsearch_version }}.deb
        - https://download.elasticsearch.org/kibana/kibana/{{ kibana_version }}.tar.gz
        - http://www.elastic.co/guide/en/kibana/3.0/snippets/shakespeare.json
    - name: "OpenJDKをインストール"
      apt: name={{ item }} install_recommends=False cache_valid_time=300
      with_items:
        - openjdk-7-jre-headless
    - name: "Elasticsearchをdebパッケージからインストール"
      apt: deb=/tmp/{{ elasticsearch_version }}.deb
    - name: "Elasticsearchを起動してサービスを有効化"
      service: name=elasticsearch state=started enabled=yes
    - name: "Elasticsearchの起動を待つ"
      wait_for: port=9200
    - name: "Kibana4のアーカイブを展開"
      unarchive: copy=no src=/tmp/{{ kibana_version }}.tar.gz dest=/opt
    - name: "Kibana4の起動スクリプトを転送"
      template: src=templates/kibana.initscript dest=/etc/init.d/kibana mode=755
    - name: "Kibana4を起動してサービスを有効化"
      service: name=kibana state=started enabled=yes
    - name: "テストデータのマッピングを作成。これを作成しないとspeakerやplay_nameがトークナイズされてしまう"
      shell: curl -XPUT http://localhost:9200/shakespeare -d '{"mappings":{"_default_":{"properties":{"speaker":{"type":"string","index":"not_analyzed" },"play_name":{"type":"string","index":"not_analyzed"},"line_id":{"type":"integer"},"speech_number":{"type":"integer"}}}}}'
    - name: "テストデータの投入"
      shell: curl -XPUT localhost:9200/_bulk --data-binary @/tmp/shakespeare.json
